import { BeadColor } from '@/types';

export const artkalPalette: BeadColor[] = [
    { id: 'A-S01', name: 'White', nameZh: '白色', hex: '#FAFAFA', brand: 'Artkal' },
    { id: 'A-S02', name: 'Ivory', nameZh: '象牙白', hex: '#FFFFF0', brand: 'Artkal' },
    { id: 'A-S03', name: 'Cream Yellow', nameZh: '奶黄', hex: '#FFF8DC', brand: 'Artkal' },
    { id: 'A-S04', name: 'Lemon Yellow', nameZh: '柠檬黄', hex: '#FFF44F', brand: 'Artkal' },
    { id: 'A-S05', name: 'Yellow', nameZh: '黄色', hex: '#FFD700', brand: 'Artkal' },
    { id: 'A-S06', name: 'Light Orange', nameZh: '浅橙', hex: '#FFA040', brand: 'Artkal' },
    { id: 'A-S07', name: 'Orange', nameZh: '橙色', hex: '#FF6600', brand: 'Artkal' },
    { id: 'A-S08', name: 'Dark Orange', nameZh: '深橙', hex: '#CC4400', brand: 'Artkal' },
    { id: 'A-S09', name: 'Light Red', nameZh: '浅红', hex: '#FF4444', brand: 'Artkal' },
    { id: 'A-S10', name: 'Red', nameZh: '红色', hex: '#DD0000', brand: 'Artkal' },
    { id: 'A-S11', name: 'Dark Red', nameZh: '深红', hex: '#990000', brand: 'Artkal' },
    { id: 'A-S12', name: 'Wine Red', nameZh: '酒红', hex: '#722F37', brand: 'Artkal' },
    { id: 'A-S13', name: 'Light Pink', nameZh: '浅粉', hex: '#FFB6C1', brand: 'Artkal' },
    { id: 'A-S14', name: 'Baby Pink', nameZh: '婴儿粉', hex: '#FF9EB5', brand: 'Artkal' },
    { id: 'A-S15', name: 'Pink', nameZh: '粉色', hex: '#FF69B4', brand: 'Artkal' },
    { id: 'A-S16', name: 'Hot Pink', nameZh: '热粉', hex: '#FF007F', brand: 'Artkal' },
    { id: 'A-S17', name: 'Magenta', nameZh: '洋红', hex: '#FF00BB', brand: 'Artkal' },
    { id: 'A-S18', name: 'Fuchsia', nameZh: '品红', hex: '#CC0077', brand: 'Artkal' },
    { id: 'A-S19', name: 'Light Purple', nameZh: '浅紫', hex: '#DA8FE5', brand: 'Artkal' },
    { id: 'A-S20', name: 'Lavender', nameZh: '薰衣草', hex: '#B57BCC', brand: 'Artkal' },
    { id: 'A-S21', name: 'Purple', nameZh: '紫色', hex: '#8B008B', brand: 'Artkal' },
    { id: 'A-S22', name: 'Dark Purple', nameZh: '深紫', hex: '#4B0082', brand: 'Artkal' },
    { id: 'A-S23', name: 'Violet', nameZh: '蓝紫', hex: '#6A0DAD', brand: 'Artkal' },
    { id: 'A-S24', name: 'Periwinkle', nameZh: '长春花蓝', hex: '#CCCCFF', brand: 'Artkal' },
    { id: 'A-S25', name: 'Light Lavender', nameZh: '淡薰衣草', hex: '#E6D5FA', brand: 'Artkal' },
    { id: 'A-S26', name: 'Sky Blue', nameZh: '天空蓝', hex: '#87CEEB', brand: 'Artkal' },
    { id: 'A-S27', name: 'Light Blue', nameZh: '浅蓝', hex: '#4DA6FF', brand: 'Artkal' },
    { id: 'A-S28', name: 'Blue', nameZh: '蓝色', hex: '#0055CC', brand: 'Artkal' },
    { id: 'A-S29', name: 'Royal Blue', nameZh: '皇家蓝', hex: '#003399', brand: 'Artkal' },
    { id: 'A-S30', name: 'Navy Blue', nameZh: '海军蓝', hex: '#001F5B', brand: 'Artkal' },
    { id: 'A-S31', name: 'Midnight Blue', nameZh: '午夜蓝', hex: '#191970', brand: 'Artkal' },
    { id: 'A-S32', name: 'Cyan', nameZh: '青色', hex: '#00CCFF', brand: 'Artkal' },
    { id: 'A-S33', name: 'Aqua', nameZh: '水蓝', hex: '#00BBCC', brand: 'Artkal' },
    { id: 'A-S34', name: 'Turquoise', nameZh: '绿松石', hex: '#40E0D0', brand: 'Artkal' },
    { id: 'A-S35', name: 'Teal', nameZh: '蓝绿', hex: '#008080', brand: 'Artkal' },
    { id: 'A-S36', name: 'Mint', nameZh: '薄荷', hex: '#AAF0C4', brand: 'Artkal' },
    { id: 'A-S37', name: 'Light Green', nameZh: '浅绿', hex: '#90EE90', brand: 'Artkal' },
    { id: 'A-S38', name: 'Lime Green', nameZh: '酸橙绿', hex: '#32CD32', brand: 'Artkal' },
    { id: 'A-S39', name: 'Green', nameZh: '绿色', hex: '#008000', brand: 'Artkal' },
    { id: 'A-S40', name: 'Dark Green', nameZh: '深绿', hex: '#006400', brand: 'Artkal' },
    { id: 'A-S41', name: 'Forest Green', nameZh: '森林绿', hex: '#228B22', brand: 'Artkal' },
    { id: 'A-S42', name: 'Olive Green', nameZh: '橄榄绿', hex: '#6B8E23', brand: 'Artkal' },
    { id: 'A-S43', name: 'Yellow Green', nameZh: '黄绿', hex: '#ADFF2F', brand: 'Artkal' },
    { id: 'A-S44', name: 'Grass Green', nameZh: '草绿', hex: '#7CFC00', brand: 'Artkal' },
    { id: 'A-S45', name: 'Sage', nameZh: '鼠尾草绿', hex: '#B2AC88', brand: 'Artkal' },
    { id: 'A-S46', name: 'Khaki', nameZh: '卡其', hex: '#C3B091', brand: 'Artkal' },
    { id: 'A-S47', name: 'Light Brown', nameZh: '浅棕', hex: '#C4A265', brand: 'Artkal' },
    { id: 'A-S48', name: 'Tan', nameZh: '棕褐', hex: '#D2B48C', brand: 'Artkal' },
    { id: 'A-S49', name: 'Brown', nameZh: '棕色', hex: '#8B4513', brand: 'Artkal' },
    { id: 'A-S50', name: 'Dark Brown', nameZh: '深棕', hex: '#5C3317', brand: 'Artkal' },
    { id: 'A-S51', name: 'Chocolate', nameZh: '巧克力', hex: '#3D1C02', brand: 'Artkal' },
    { id: 'A-S52', name: 'Caramel', nameZh: '焦糖', hex: '#C68400', brand: 'Artkal' },
    { id: 'A-S53', name: 'Peach', nameZh: '桃色', hex: '#FFDAB9', brand: 'Artkal' },
    { id: 'A-S54', name: 'Skin', nameZh: '肤色', hex: '#FFD5A0', brand: 'Artkal' },
    { id: 'A-S55', name: 'Dark Skin', nameZh: '深肤色', hex: '#C68840', brand: 'Artkal' },
    { id: 'A-S56', name: 'Light Gray', nameZh: '浅灰', hex: '#DCDCDC', brand: 'Artkal' },
    { id: 'A-S57', name: 'Silver', nameZh: '银灰', hex: '#C0C0C0', brand: 'Artkal' },
    { id: 'A-S58', name: 'Gray', nameZh: '灰色', hex: '#808080', brand: 'Artkal' },
    { id: 'A-S59', name: 'Dark Gray', nameZh: '深灰', hex: '#404040', brand: 'Artkal' },
    { id: 'A-S60', name: 'Black', nameZh: '黑色', hex: '#111111', brand: 'Artkal' },
    { id: 'A-S61', name: 'Gold', nameZh: '金色', hex: '#FFD700', brand: 'Artkal' },
    { id: 'A-S62', name: 'Sand', nameZh: '沙色', hex: '#C2B280', brand: 'Artkal' },
    { id: 'A-S63', name: 'Coral', nameZh: '珊瑚红', hex: '#FF7F50', brand: 'Artkal' },
    { id: 'A-S64', name: 'Salmon', nameZh: '鲑鱼粉', hex: '#FA8072', brand: 'Artkal' },
];
