import { BeadColor } from '@/types';

export const hamaPalette: BeadColor[] = [
    { id: 'H-01', name: 'White', nameZh: '白色', hex: '#F8F8F8', brand: 'Hama' },
    { id: 'H-02', name: 'Cream', nameZh: '奶油', hex: '#FFF5CC', brand: 'Hama' },
    { id: 'H-03', name: 'Yellow', nameZh: '黄色', hex: '#FFE619', brand: 'Hama' },
    { id: 'H-04', name: 'Orange', nameZh: '橙色', hex: '#FF7A00', brand: 'Hama' },
    { id: 'H-05', name: 'Red', nameZh: '红色', hex: '#CC0000', brand: 'Hama' },
    { id: 'H-06', name: 'Pink', nameZh: '粉色', hex: '#FF7BAC', brand: 'Hama' },
    { id: 'H-07', name: 'Fuchsia', nameZh: '品红', hex: '#E2007A', brand: 'Hama' },
    { id: 'H-08', name: 'Purple', nameZh: '紫色', hex: '#800080', brand: 'Hama' },
    { id: 'H-09', name: 'Dark Lilac', nameZh: '深紫', hex: '#5E2C7A', brand: 'Hama' },
    { id: 'H-10', name: 'Dark Blue', nameZh: '深蓝', hex: '#1A237E', brand: 'Hama' },
    { id: 'H-11', name: 'Blue', nameZh: '蓝色', hex: '#1565C0', brand: 'Hama' },
    { id: 'H-12', name: 'Light Blue', nameZh: '浅蓝', hex: '#42A5F5', brand: 'Hama' },
    { id: 'H-13', name: 'Turquoise', nameZh: '青绿', hex: '#00ACC1', brand: 'Hama' },
    { id: 'H-14', name: 'Green', nameZh: '绿色', hex: '#2E7D32', brand: 'Hama' },
    { id: 'H-15', name: 'Light Green', nameZh: '浅绿', hex: '#66BB6A', brand: 'Hama' },
    { id: 'H-16', name: 'Yellow-Green', nameZh: '黄绿', hex: '#CDDC39', brand: 'Hama' },
    { id: 'H-17', name: 'Dark Green', nameZh: '深绿', hex: '#1B5E20', brand: 'Hama' },
    { id: 'H-18', name: 'Olive', nameZh: '橄榄', hex: '#827717', brand: 'Hama' },
    { id: 'H-19', name: 'Brown', nameZh: '棕色', hex: '#8D6E63', brand: 'Hama' },
    { id: 'H-20', name: 'Dark Brown', nameZh: '深棕', hex: '#4E342E', brand: 'Hama' },
    { id: 'H-21', name: 'Black', nameZh: '黑色', hex: '#212121', brand: 'Hama' },
    { id: 'H-22', name: 'Dark Gray', nameZh: '深灰', hex: '#616161', brand: 'Hama' },
    { id: 'H-23', name: 'Gray', nameZh: '灰色', hex: '#9E9E9E', brand: 'Hama' },
    { id: 'H-24', name: 'Light Gray', nameZh: '浅灰', hex: '#E0E0E0', brand: 'Hama' },
    { id: 'H-25', name: 'Skin Tone', nameZh: '肤色', hex: '#FFCCAA', brand: 'Hama' },
    { id: 'H-26', name: 'Sand', nameZh: '沙色', hex: '#D7B28A', brand: 'Hama' },
    { id: 'H-27', name: 'Dark Beige', nameZh: '深米色', hex: '#A08060', brand: 'Hama' },
    { id: 'H-28', name: 'Caramel', nameZh: '焦糖', hex: '#C68428', brand: 'Hama' },
    { id: 'H-29', name: 'Gold', nameZh: '金色', hex: '#FFD600', brand: 'Hama' },
    { id: 'H-30', name: 'Silver', nameZh: '银色', hex: '#CFD8DC', brand: 'Hama' },
    { id: 'H-31', name: 'Pastel Yellow', nameZh: '粉黄', hex: '#FFF9C4', brand: 'Hama' },
    { id: 'H-32', name: 'Pastel Green', nameZh: '粉绿', hex: '#C8E6C9', brand: 'Hama' },
    { id: 'H-33', name: 'Pastel Blue', nameZh: '粉蓝', hex: '#BBDEFB', brand: 'Hama' },
    { id: 'H-34', name: 'Pastel Pink', nameZh: '粉粉', hex: '#F8BBD0', brand: 'Hama' },
    { id: 'H-35', name: 'Pastel Lilac', nameZh: '粉紫', hex: '#E1BEE7', brand: 'Hama' },
    { id: 'H-36', name: 'Peach', nameZh: '桃色', hex: '#FFCCBC', brand: 'Hama' },
    { id: 'H-37', name: 'Mint', nameZh: '薄荷', hex: '#B2DFDB', brand: 'Hama' },
    { id: 'H-38', name: 'Lilac', nameZh: '丁香紫', hex: '#CE93D8', brand: 'Hama' },
    { id: 'H-39', name: 'Marine Blue', nameZh: '海军蓝', hex: '#0D47A1', brand: 'Hama' },
    { id: 'H-40', name: 'Dark Red', nameZh: '暗红', hex: '#B71C1C', brand: 'Hama' },
    { id: 'H-41', name: 'Burgundy', nameZh: '酒红', hex: '#7B1FA2', brand: 'Hama' },
    { id: 'H-42', name: 'Terracotta', nameZh: '赤陶', hex: '#BF360C', brand: 'Hama' },
    { id: 'H-43', name: 'Wheat', nameZh: '小麦', hex: '#F5DEB3', brand: 'Hama' },
    { id: 'H-44', name: 'Teal', nameZh: '青色', hex: '#00695C', brand: 'Hama' },
    { id: 'H-45', name: 'Cyan', nameZh: '青蓝', hex: '#00BCD4', brand: 'Hama' },
    { id: 'H-46', name: 'Forest Green', nameZh: '森林绿', hex: '#388E3C', brand: 'Hama' },
    { id: 'H-47', name: 'Lime', nameZh: '柠檬绿', hex: '#76FF03', brand: 'Hama' },
    { id: 'H-48', name: 'Coral', nameZh: '珊瑚', hex: '#FF6E40', brand: 'Hama' },
    { id: 'H-49', name: 'Salmon', nameZh: '鲑鱼粉', hex: '#FF8A65', brand: 'Hama' },
    { id: 'H-50', name: 'Mauve', nameZh: '木槿紫', hex: '#CE93D8', brand: 'Hama' },
    { id: 'H-51', name: 'Dark Orange', nameZh: '深橙', hex: '#E64A19', brand: 'Hama' },
    { id: 'H-52', name: 'Cobalt', nameZh: '钴蓝', hex: '#3949AB', brand: 'Hama' },
    { id: 'H-53', name: 'Neon Green', nameZh: '荧光绿', hex: '#76FF03', brand: 'Hama' },
    { id: 'H-54', name: 'Neon Yellow', nameZh: '荧光黄', hex: '#F4FF81', brand: 'Hama' },
    { id: 'H-55', name: 'Neon Pink', nameZh: '荧光粉', hex: '#FF4081', brand: 'Hama' },
    { id: 'H-56', name: 'Neon Orange', nameZh: '荧光橙', hex: '#FF6D00', brand: 'Hama' },
    { id: 'H-57', name: 'Gunmetal', nameZh: '枪灰', hex: '#546E7A', brand: 'Hama' },
    { id: 'H-58', name: 'Almond', nameZh: '杏仁', hex: '#FFECB3', brand: 'Hama' },
    { id: 'H-59', name: 'Lemon', nameZh: '柠檬黄', hex: '#FFF176', brand: 'Hama' },
    { id: 'H-60', name: 'Crimson', nameZh: '深红', hex: '#C62828', brand: 'Hama' },
];
