import { BeadColor } from '@/types';

export const perlerPalette: BeadColor[] = [
  { id: 'P-17706', name: 'White', nameZh: '白色', hex: '#FFFFFF', brand: 'Perler' },
  { id: 'P-17707', name: 'Cream', nameZh: '奶油色', hex: '#FFF8DC', brand: 'Perler' },
  { id: 'P-17708', name: 'Pastel Yellow', nameZh: '粉黄', hex: '#FFFAAA', brand: 'Perler' },
  { id: 'P-17709', name: 'Yellow', nameZh: '黄色', hex: '#FFE135', brand: 'Perler' },
  { id: 'P-17710', name: 'Yellow Orange', nameZh: '橙黄', hex: '#FFAA00', brand: 'Perler' },
  { id: 'P-17711', name: 'Orange', nameZh: '橙色', hex: '#FF7300', brand: 'Perler' },
  { id: 'P-17712', name: 'Rust', nameZh: '锈红', hex: '#B7410E', brand: 'Perler' },
  { id: 'P-17713', name: 'Red', nameZh: '红色', hex: '#DD0000', brand: 'Perler' },
  { id: 'P-17714', name: 'Pastel Pink', nameZh: '粉红', hex: '#FFB5C8', brand: 'Perler' },
  { id: 'P-17715', name: 'Pink', nameZh: '粉色', hex: '#FF69B4', brand: 'Perler' },
  { id: 'P-17716', name: 'Hot Coral', nameZh: '珊瑚红', hex: '#FF4B4B', brand: 'Perler' },
  { id: 'P-17717', name: 'Magenta', nameZh: '洋红', hex: '#CC0066', brand: 'Perler' },
  { id: 'P-17718', name: 'Purple', nameZh: '紫色', hex: '#7B2FBE', brand: 'Perler' },
  { id: 'P-17719', name: 'Pastel Lavender', nameZh: '薰衣草', hex: '#D8B4FE', brand: 'Perler' },
  { id: 'P-17720', name: 'Lavender', nameZh: '淡紫', hex: '#9B59B6', brand: 'Perler' },
  { id: 'P-17721', name: 'Pastel Blue', nameZh: '粉蓝', hex: '#AED6F1', brand: 'Perler' },
  { id: 'P-17722', name: 'Light Blue', nameZh: '浅蓝', hex: '#5DADE2', brand: 'Perler' },
  { id: 'P-17723', name: 'Blue', nameZh: '蓝色', hex: '#2471A3', brand: 'Perler' },
  { id: 'P-17724', name: 'Dark Blue', nameZh: '深蓝', hex: '#1A3A6B', brand: 'Perler' },
  { id: 'P-17725', name: 'Navy', nameZh: '海军蓝', hex: '#1B2A4A', brand: 'Perler' },
  { id: 'P-17726', name: 'Pastel Green', nameZh: '粉绿', hex: '#ABEBC6', brand: 'Perler' },
  { id: 'P-17727', name: 'Light Green', nameZh: '浅绿', hex: '#52BE80', brand: 'Perler' },
  { id: 'P-17728', name: 'Green', nameZh: '绿色', hex: '#1E8449', brand: 'Perler' },
  { id: 'P-17729', name: 'Dark Green', nameZh: '深绿', hex: '#145A32', brand: 'Perler' },
  { id: 'P-17730', name: 'Camo', nameZh: '迷彩绿', hex: '#4A5E3A', brand: 'Perler' },
  { id: 'P-17731', name: 'Olive', nameZh: '橄榄绿', hex: '#808000', brand: 'Perler' },
  { id: 'P-17732', name: 'Pastel Mint', nameZh: '薄荷绿', hex: '#B2EBE0', brand: 'Perler' },
  { id: 'P-17733', name: 'Teal', nameZh: '青绿', hex: '#008080', brand: 'Perler' },
  { id: 'P-17734', name: 'Turquoise', nameZh: '绿松石', hex: '#00CED1', brand: 'Perler' },
  { id: 'P-17735', name: 'Cyan', nameZh: '青色', hex: '#00BFFF', brand: 'Perler' },
  { id: 'P-17736', name: 'Caramel', nameZh: '焦糖', hex: '#C68642', brand: 'Perler' },
  { id: 'P-17737', name: 'Brown', nameZh: '棕色', hex: '#8B4513', brand: 'Perler' },
  { id: 'P-17738', name: 'Dark Brown', nameZh: '深棕', hex: '#4A2C0A', brand: 'Perler' },
  { id: 'P-17739', name: 'Sand', nameZh: '沙色', hex: '#C2B280', brand: 'Perler' },
  { id: 'P-17740', name: 'Tan', nameZh: '棕褐', hex: '#D2B48C', brand: 'Perler' },
  { id: 'P-17741', name: 'Toasted Marshmallow', nameZh: '棉花糖', hex: '#F5DEB3', brand: 'Perler' },
  { id: 'P-17742', name: 'Peach', nameZh: '桃色', hex: '#FFCBA4', brand: 'Perler' },
  { id: 'P-17743', name: 'Skin Tone', nameZh: '肤色', hex: '#FFD5B2', brand: 'Perler' },
  { id: 'P-17744', name: 'Light Gray', nameZh: '浅灰', hex: '#D5D8DC', brand: 'Perler' },
  { id: 'P-17745', name: 'Gray', nameZh: '灰色', hex: '#909497', brand: 'Perler' },
  { id: 'P-17746', name: 'Dark Gray', nameZh: '深灰', hex: '#566573', brand: 'Perler' },
  { id: 'P-17747', name: 'Silver', nameZh: '银色', hex: '#BDC3C7', brand: 'Perler' },
  { id: 'P-17748', name: 'Black', nameZh: '黑色', hex: '#1C1C1C', brand: 'Perler' },
  { id: 'P-17749', name: 'Gold', nameZh: '金色', hex: '#FFD700', brand: 'Perler' },
  { id: 'P-17750', name: 'Copper', nameZh: '铜色', hex: '#B87333', brand: 'Perler' },
  { id: 'P-17751', name: 'Blush', nameZh: '玫瑰红', hex: '#E8A0BF', brand: 'Perler' },
  { id: 'P-17752', name: 'Bubblegum', nameZh: '泡泡糖', hex: '#FF85C2', brand: 'Perler' },
  { id: 'P-17753', name: 'Grape', nameZh: '葡萄紫', hex: '#6F2DA8', brand: 'Perler' },
  { id: 'P-17754', name: 'Pool Blue', nameZh: '泳池蓝', hex: '#4FB3E8', brand: 'Perler' },
  { id: 'P-17755', name: 'Midnight', nameZh: '午夜蓝', hex: '#1C2951', brand: 'Perler' },
  { id: 'P-17756', name: 'Robin Egg', nameZh: '蛋壳蓝', hex: '#1FCECB', brand: 'Perler' },
  { id: 'P-17757', name: 'Shamrock', nameZh: '三叶草绿', hex: '#009A44', brand: 'Perler' },
  { id: 'P-17758', name: 'Artichoke', nameZh: '朝鲜蓟绿', hex: '#8F9779', brand: 'Perler' },
  { id: 'P-17759', name: 'Eggplant', nameZh: '茄子紫', hex: '#614051', brand: 'Perler' },
  { id: 'P-17760', name: 'Terracotta', nameZh: '赤陶', hex: '#CC4E2A', brand: 'Perler' },
  { id: 'P-17761', name: 'Maize', nameZh: '玉米黄', hex: '#FBEC5D', brand: 'Perler' },
  { id: 'P-17762', name: 'Flamingo', nameZh: '火烈鸟粉', hex: '#FC8EAC', brand: 'Perler' },
  { id: 'P-17763', name: 'Prickly Pear', nameZh: '仙人掌绿', hex: '#84C78B', brand: 'Perler' },
  { id: 'P-17764', name: 'Light Brown', nameZh: '浅棕', hex: '#A0522D', brand: 'Perler' },
  { id: 'P-17765', name: 'Kiwi', nameZh: '奇异果绿', hex: '#8CC63F', brand: 'Perler' },
  { id: 'P-17766', name: 'Berry', nameZh: '浆果紫', hex: '#8B0057', brand: 'Perler' },
];
